### ISSUE TITLE
Capture images using Camera 

### ISSUE THREAD

**Issue by amgad-div** [karunakaran186/KAVI-voice-Assitant#31] opened 2022-03-02 15:49 UTC
To capture the image using webcam using Python Assistant, ecapture module of python is implemented
Please assign this issue to me

**Comment by amgad-div** [comment] 2022-03-02 15:50
if image contian a text we can translate it

**Comment by HarshKumarChoudary** [comment] 2022-03-05 01:35
I would like to work on this issue. I'm a GSSOC 22 participant. Please assign it to me, if the issue is not resolved. Thanks.

**Comment by amgad-div** [comment] 2022-03-05 13:56
i am working on it

**Closed** 2022-03-12 19:27 UTC
Labels: Gssoc 2022, level 1
